In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.pipeline import Pipeline

In [16]:
df = pd.read_csv('Advertising.csv')
df.head()

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  200 non-null    int64
 1   TV          200 non-null    float64
 2   Radio       200 non-null    float64
 3   Newspaper   200 non-null    float64
 4   Sales       200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB

In [18]:
df.isnull().sum()

Unnamed: 0    0
TV            0
Radio         0
Newspaper     0
Sales         0
dtype: int64

In [19]:
df = df.drop('Unnamed: 0',axis=1)

In [20]:
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [21]:
x  = df.drop('Sales',axis=1)
y = df['Sales']

In [22]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [29]:
preprocessor = ColumnTransformer(
    transformers=
    [
        ('scale',StandardScaler(),['TV','Radio','Newspaper'])
    ]
)

In [30]:
pipeline = Pipeline(
    [
        ('transform',preprocessor),
        ('model',LinearRegression())
    ]
)

In [31]:
pipeline.fit(x_train,y_train)

Pipeline(steps=[('transform',
                 ColumnTransformer(transformers=[('scale', StandardScaler(),
                                                  ['TV', 'Radio',
                                                   'Newspaper'])])),
                ('model', LinearRegression())])

In [33]:
y_pred = pipeline.predict(x_test)

In [34]:
print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", mean_squared_error(y_test, y_pred) ** 0.5)

R2 Score: 0.8994380241009119
MAE: 1.4607567168117601
RMSE: 1.781599661533451